name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          working-directory: thank_you_diary_mvp

      - run: bundle install
        working-directory: thank_you_diary_mvp

      - run: bin/brakeman --no-pager || true
        working-directory: thank_you_diary_mvp

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - run: bundle install
        working-directory: thank_you_diary_mvp

      - run: bin/importmap audit
        working-directory: thank_you_diary_mvp

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - run: bundle install
        working-directory: thank_you_diary_mvp

      - run: bin/rubocop -f github
        working-directory: thank_you_diary_mvp

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - run: bundle install
        working-directory: thank_you_diary_mvp

      - run: bin/rails db:create
        working-directory: thank_you_diary_mvp
        env:
          RAILS_ENV: test

      - run: bin/rails db:migrate
        working-directory: thank_you_diary_mvp
        env:
          RAILS_ENV: test

      - run: bundle exec rspec
        working-directory: thank_you_diary_mvp
        env:
          RAILS_ENV: test